"""
test_v260.py — InScript v2.6.0
============================================================
Package Ecosystem tests:
  • Scoped package parsing (@scope/name, @scope/name@version)
  • Config system (set/get/list/unset, private registry URL)
  • publish_package() (local bundle + SHA-256, no live network required)
  • audit_packages()  (offline structural check + advisory matching)
  • Monorepo / workspace support (resolve members, workspace_install)
  • Stdlib versioning (satisfies / mismatch / missing)
  • _pkg_to_dir_name() mapping
  • _get_registry_url() honours config override

All tests run without network access. Registry and advisory calls are
stubbed via a temp file-based registry or monkey-patching.
"""
import sys, os, json, tempfile, shutil, hashlib
sys.path.insert(0, os.path.dirname(__file__))

from inscript import (
    _parse_pkg_spec,
    _pkg_to_dir_name,
    _read_config,
    _write_config,
    _get_registry_url,
    cmd_config,
    publish_package,
    audit_packages,
    _resolve_workspace_packages,
    workspace_list,
    workspace_install,
    check_stdlib_version,
    _parse_toml_simple,
    MANIFEST_FILENAME,
    LOCK_FILENAME,
    REGISTRY_URL,
    CONFIG_PATH,
)

PASS = 0; FAIL = 0

def ok(name):
    global PASS; PASS += 1; print(f"  PASS  {name}")

def fail(name, msg=""):
    global FAIL; FAIL += 1; print(f"  FAIL  {name}: {msg}")

def check(name, got, expected):
    if got == expected: ok(name)
    else: fail(name, f"want {expected!r}, got {got!r}")

def check_contains(name, text, substring):
    if substring in text: ok(name)
    else: fail(name, f"expected {substring!r} in {text!r}")

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def make_tmpdir() -> str:
    return tempfile.mkdtemp(prefix="inscript_test_")

def write_toml(directory: str, content: str):
    with open(os.path.join(directory, MANIFEST_FILENAME), "w") as f:
        f.write(content)

def write_lock(directory: str, entries: dict):
    """Write inscript.lock in the real TOML format that _read_lock expects."""
    import hashlib, datetime
    lines = [
        "# InScript lockfile — do not edit manually\n",
        "# Generated by test_v260.py\n\n",
        "[metadata]\n",
        'inscript  = "2.6.0"\n',
        f'generated = "{datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")}"\n\n',
    ]
    for pkg_name, version in entries.items():
        sha256 = hashlib.sha256(f"{pkg_name}@{version}".encode()).hexdigest()
        lines.append(f"[package.{pkg_name}]\n")
        lines.append(f'version = "{version}"\n')
        lines.append(f'sha256  = "{sha256}"\n\n')
    with open(os.path.join(directory, LOCK_FILENAME), "w") as f:
        f.writelines(lines)

# ─────────────────────────────────────────────────────────────────────────────
# 1. Scoped package parsing
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 1. Scoped package parsing ──────────────────────────────────────────")

check("plain name",              _parse_pkg_spec("math-utils"),              ("math-utils", None))
check("plain name@version",      _parse_pkg_spec("math-utils@1.2.0"),        ("math-utils", "1.2.0"))
check("scoped no version",       _parse_pkg_spec("@authorss81/ecs"),         ("@authorss81/ecs", None))
check("scoped @version",         _parse_pkg_spec("@authorss81/ecs@2.0.0"),   ("@authorss81/ecs", "2.0.0"))
check("community scope",         _parse_pkg_spec("@community/pathfinding"),  ("@community/pathfinding", None))
check("community scope version", _parse_pkg_spec("@community/pathfinding@0.9.1"),
                                                                              ("@community/pathfinding", "0.9.1"))
check("whitespace stripped",     _parse_pkg_spec("  math-utils@1.0.0  "),    ("math-utils", "1.0.0"))

# ─────────────────────────────────────────────────────────────────────────────
# 2. _pkg_to_dir_name
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 2. _pkg_to_dir_name ────────────────────────────────────────────────")

check("plain unchanged",      _pkg_to_dir_name("math-utils"),        "math-utils")
check("scoped flattened",     _pkg_to_dir_name("@authorss81/ecs"),   "authorss81__ecs")
check("community flattened",  _pkg_to_dir_name("@community/grid"),   "community__grid")

# ─────────────────────────────────────────────────────────────────────────────
# 3. Config system
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 3. Config system ───────────────────────────────────────────────────")

# Use a temp config path to avoid polluting real user config
import inscript as _ins_mod
_orig_config_path = _ins_mod.CONFIG_PATH
_tmp_config_dir   = make_tmpdir()
_ins_mod.CONFIG_PATH = os.path.join(_tmp_config_dir, "config.json")

try:
    # Fresh config is empty
    cfg = _read_config()
    check("fresh config is empty dict", cfg, {})

    # set
    ret = cmd_config(["set", "registry", "https://pkg.mygame.dev"])
    check("config set returns 0", ret, 0)

    cfg2 = _read_config()
    check("registry value stored", cfg2.get("registry"), "https://pkg.mygame.dev")

    # get
    import io as _io
    old_stdout = sys.stdout
    sys.stdout = _io.StringIO()
    cmd_config(["get", "registry"])
    out = sys.stdout.getvalue().strip()
    sys.stdout = old_stdout
    check("config get prints value", out, "https://pkg.mygame.dev")

    # list
    sys.stdout = _io.StringIO()
    cmd_config(["list"])
    out2 = sys.stdout.getvalue()
    sys.stdout = old_stdout
    check_contains("config list shows key", out2, "registry")
    check_contains("config list shows value", out2, "https://pkg.mygame.dev")

    # _get_registry_url honours override
    url = _get_registry_url()
    check("_get_registry_url uses config override", url, "https://pkg.mygame.dev")

    # unset
    cmd_config(["unset", "registry"])
    cfg3 = _read_config()
    check("config unset removes key", "registry" in cfg3, False)

    # _get_registry_url falls back to default after unset
    url2 = _get_registry_url()
    check("_get_registry_url falls back to default", url2, REGISTRY_URL)

    # unknown subcommand
    ret_bad = cmd_config(["badcmd"])
    check("unknown subcommand returns 1", ret_bad, 1)

    # missing args
    ret_nokey = cmd_config(["set", "only_one_arg"])
    check("set with missing value returns 1", ret_nokey, 1)

finally:
    _ins_mod.CONFIG_PATH = _orig_config_path
    shutil.rmtree(_tmp_config_dir, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# 4. publish_package() — local bundle validation (no live network)
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 4. publish_package() ───────────────────────────────────────────────")

_tmp_pub = make_tmpdir()
_tmp_cfg_pub = make_tmpdir()
_ins_mod.CONFIG_PATH = os.path.join(_tmp_cfg_pub, "config.json")

try:
    # Missing inscript.toml → error
    ret_no_toml = publish_package(_tmp_pub)
    check("publish with no toml returns 1", ret_no_toml, 1)

    # toml with no [package] name → error
    write_toml(_tmp_pub, "[package]\nversion = \"1.0.0\"\n")
    ret_no_name = publish_package(_tmp_pub)
    check("publish with no name returns 1", ret_no_name, 1)

    # toml with name but no version → error
    write_toml(_tmp_pub, "[package]\nname = \"my-pkg\"\n")
    ret_no_ver = publish_package(_tmp_pub)
    check("publish with no version returns 1", ret_no_ver, 1)

    # valid toml but no api_key → error
    write_toml(_tmp_pub, "[package]\nname = \"my-pkg\"\nversion = \"1.0.0\"\n")
    os.makedirs(os.path.dirname(_ins_mod.CONFIG_PATH), exist_ok=True)
    ret_no_key = publish_package(_tmp_pub)
    check("publish with no api_key returns 1", ret_no_key, 1)

    # Set api_key and add a .ins file — bundle should form; upload will fail (no registry)
    _ins_mod._write_config({"api_key": "test-token-xyz"})
    with open(os.path.join(_tmp_pub, "main.ins"), "w") as f:
        f.write("let x = 42\nprint(x)\n")
    ret_pub = publish_package(_tmp_pub)
    # Should return 1 (registry not live) but reach the upload step (sha256 printed)
    check("publish reaches upload step (returns 1 = registry not live)", ret_pub, 1)

    # No .ins files → error before upload
    tmp_empty = make_tmpdir()
    write_toml(tmp_empty, "[package]\nname = \"empty\"\nversion = \"0.1.0\"\n")
    ret_empty = publish_package(tmp_empty)
    check("publish with no .ins files returns 1", ret_empty, 1)
    shutil.rmtree(tmp_empty, ignore_errors=True)

finally:
    _ins_mod.CONFIG_PATH = _orig_config_path
    shutil.rmtree(_tmp_pub, ignore_errors=True)
    shutil.rmtree(_tmp_cfg_pub, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# 5. audit_packages() — offline structural checks
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 5. audit_packages() ────────────────────────────────────────────────")

_tmp_audit = make_tmpdir()

try:
    # No lock file → clean exit
    ret_no_lock = audit_packages(_tmp_audit)
    check("audit with no lock returns 0", ret_no_lock, 0)

    # Empty lock (no packages) → clean
    write_lock(_tmp_audit, {})
    ret_empty_lock = audit_packages(_tmp_audit)
    check("audit with empty lock returns 0", ret_empty_lock, 0)

    # Lock with packages but no advisory file (offline) → prints warning, returns 0
    write_lock(_tmp_audit, {"math-utils": "1.0.0", "color-utils": "1.0.0"})
    # Stub ADVISORY_URL to a non-existent file so it falls through to offline mode
    old_adv_url = _ins_mod.ADVISORY_URL
    _ins_mod.ADVISORY_URL = "https://localhost:0/advisories_nonexistent.json"
    ret_offline = audit_packages(_tmp_audit)
    _ins_mod.ADVISORY_URL = old_adv_url
    # Offline: no vulns from advisory DB but may warn about missing dirs → return 0
    check("audit offline (no network) returns 0", ret_offline, 0)

    # Advisory matching via a temp file patched in
    adv_data = {
        "math-utils": [
            {
                "affected": "<1.0.1",
                "severity": "low",
                "description": "Off-by-one in gcd()",
                "fixed_in": "1.0.1"
            }
        ]
    }
    tmp_adv = os.path.join(_tmp_audit, "advisories.json")
    with open(tmp_adv, "w") as f:
        json.dump(adv_data, f)

    # Patch ADVISORY_URL to local file:// URL and lock to vulnerable version
    write_lock(_tmp_audit, {"math-utils": "1.0.0"})
    _ins_mod.ADVISORY_URL = "file://" + tmp_adv if sys.platform != "win32" else "file:///" + tmp_adv.replace("\\", "/")
    import urllib.request as _ur
    _orig_urlopen = _ur.urlopen
    def _mock_urlopen(url, timeout=None):
        # Serve our local file for advisory URL regardless of scheme
        if "advisories" in url:
            class _FakeResp:
                def read(self_): return json.dumps(adv_data).encode()
                def __enter__(self_): return self_
                def __exit__(self_, *a): pass
            return _FakeResp()
        return _orig_urlopen(url, timeout=timeout)
    _ur.urlopen = _mock_urlopen
    try:
        ret_vuln = audit_packages(_tmp_audit)
        check("audit finds vulnerability in affected package returns 1", ret_vuln, 1)
    finally:
        _ur.urlopen = _orig_urlopen
        _ins_mod.ADVISORY_URL = old_adv_url

    # Non-vulnerable version → clean
    write_lock(_tmp_audit, {"math-utils": "1.0.1"})
    _ur.urlopen = _mock_urlopen
    try:
        ret_safe = audit_packages(_tmp_audit)
        check("audit finds no vuln for patched version returns 0", ret_safe, 0)
    finally:
        _ur.urlopen = _orig_urlopen

finally:
    shutil.rmtree(_tmp_audit, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# 6. Monorepo / workspace support
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 6. Monorepo / workspace support ────────────────────────────────────")

_tmp_mono = make_tmpdir()

try:
    # No workspace key → empty list
    write_toml(_tmp_mono, "[package]\nname = \"root\"\nversion = \"1.0.0\"\n")
    members = _resolve_workspace_packages(_tmp_mono)
    check("no workspace key → empty list", members, [])

    # Create two sub-packages
    pkg_a = os.path.join(_tmp_mono, "packages", "pkg-a")
    pkg_b = os.path.join(_tmp_mono, "packages", "pkg-b")
    os.makedirs(pkg_a); os.makedirs(pkg_b)
    write_toml(pkg_a, "[package]\nname = \"pkg-a\"\nversion = \"0.1.0\"\n")
    write_toml(pkg_b, "[package]\nname = \"pkg-b\"\nversion = \"0.2.0\"\n")

    # Write root manifest with workspace glob (top-level key, not inside [package])
    write_toml(_tmp_mono, '[package]\nname = "root"\nversion = "1.0.0"\n\nworkspace = ["packages/*"]\n')

    members2 = _resolve_workspace_packages(_tmp_mono)
    names = sorted([m[0] for m in members2])
    check("workspace discovers 2 members", len(members2), 2)
    check("member names resolved", names, ["pkg-a", "pkg-b"])

    # workspace_list should return 0
    ret_list = workspace_list(_tmp_mono)
    check("workspace_list returns 0", ret_list, 0)

    # Member with no inscript.toml is skipped
    pkg_c = os.path.join(_tmp_mono, "packages", "pkg-c")
    os.makedirs(pkg_c)
    # No manifest → should be skipped
    members3 = _resolve_workspace_packages(_tmp_mono)
    check("member without toml is skipped", len(members3), 2)

    # workspace_install with no deps → 0
    ret_ws_install = workspace_install(_tmp_mono)
    check("workspace_install with no deps returns 0", ret_ws_install, 0)

finally:
    shutil.rmtree(_tmp_mono, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# 7. Stdlib versioning
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 7. Stdlib versioning ───────────────────────────────────────────────")

_tmp_stdlib = make_tmpdir()

try:
    from inscript import VERSION as _V

    # No toml → 0 (no constraint to check)
    ret_no_toml = check_stdlib_version(_tmp_stdlib)
    check("no toml → stdlib check passes", ret_no_toml, 0)

    # Toml with no stdlib key → 0
    write_toml(_tmp_stdlib, "[package]\nname = \"mygame\"\nversion = \"1.0.0\"\n")
    ret_no_key = check_stdlib_version(_tmp_stdlib)
    check("no stdlib key → passes", ret_no_key, 0)

    # Satisfied constraint (current version exactly)
    write_toml(_tmp_stdlib, f'[package]\nname = "mygame"\nversion = "1.0.0"\nstdlib = ">={_V}"\n')
    ret_ok = check_stdlib_version(_tmp_stdlib)
    check("satisfied constraint (>=current) returns 0", ret_ok, 0)

    # Unsatisfied constraint (require far-future version)
    write_toml(_tmp_stdlib, '[package]\nname = "mygame"\nversion = "1.0.0"\nstdlib = ">=99.0.0"\n')
    ret_fail = check_stdlib_version(_tmp_stdlib)
    check("unsatisfied constraint returns 1", ret_fail, 1)

    # Exact version match
    write_toml(_tmp_stdlib, f'[package]\nname = "mygame"\nversion = "1.0.0"\nstdlib = "^{_V}"\n')
    ret_caret = check_stdlib_version(_tmp_stdlib)
    check("caret constraint on current version returns 0", ret_caret, 0)

finally:
    shutil.rmtree(_tmp_stdlib, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# 8. _get_registry_url with temp config
# ─────────────────────────────────────────────────────────────────────────────
print("\n── 8. _get_registry_url ───────────────────────────────────────────────")

_tmp_cfg2 = make_tmpdir()
_ins_mod.CONFIG_PATH = os.path.join(_tmp_cfg2, "config.json")
try:
    url_default = _get_registry_url()
    check("default registry URL matches constant", url_default, REGISTRY_URL)

    _ins_mod._write_config({"registry": "https://pkg.example.com"})
    url_custom = _get_registry_url()
    check("custom registry URL from config", url_custom, "https://pkg.example.com")
finally:
    _ins_mod.CONFIG_PATH = _orig_config_path
    shutil.rmtree(_tmp_cfg2, ignore_errors=True)

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
print(f"\n{'='*60}")
total = PASS + FAIL
print(f"InScript v2.6.0  —  {PASS}/{total} tests passed", end="")
if FAIL:
    print(f"  ❌ {FAIL} FAILED")
    sys.exit(1)
else:
    print("  ✅ ALL PASS")
    sys.exit(0)
