// inscript_vm_engine/src/jit.rs
// JIT Stub Layer — InScript v3.9.1
//
// Hot-path detection and stub management layer. When a trace (linear sequence
// of opcodes) executes frequently, the JIT marks it for compilation to native
// code via LLVM IR emission. This module:
//
//   • Tracks instruction execution frequency (hot-path detection)
//   • Maintains a stub table mapping traces to native function pointers
//   • Provides fallback to VM when stubs are not yet compiled
//   • Integrates with ir.rs for code generation
//
// The JIT does NOT compile or execute native code itself (that requires LLVM
// toolchain). Instead, it marks traces as "hot" and emits IR ready for the
// build pipeline to compile offline.
//
// Usage flow:
//   1. VMEngine executes opcodes normally
//   2. JIT tracks frequency of execution paths
//   3. When a trace exceeds HOT_THRESHOLD (e.g., 1000 executions), mark hot
//   4. Store IR text in StubTable for external compilation
//   5. Once compiled, replace VM call with native function pointer
//   6. Fallback to VM if native code not yet available

use crate::OpCode;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;


// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

/// Execution count threshold before marking a trace as "hot" for compilation.
/// Typically set to 100–1000 depending on workload.
pub const HOT_THRESHOLD: u64 = 1000;

/// Maximum number of stub entries to maintain. Prevents unbounded memory growth.
pub const MAX_STUBS: usize = 256;

// ─────────────────────────────────────────────────────────────────────────────
// Trace representation
// ─────────────────────────────────────────────────────────────────────────────

/// A trace is a linear sequence of opcodes with a unique identifier.
/// Traces are extracted from the instruction stream at branching points
/// (jumps, loops) to identify hot paths.
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct TraceId(pub String);

impl TraceId {
    /// Create a trace ID from a starting instruction index.
    pub fn from_index(idx: usize) -> Self {
        TraceId(format!("trace_{}", idx))
    }

    /// Create a trace ID from a custom name (useful for named regions).
    pub fn from_name(name: impl Into<String>) -> Self {
        TraceId(name.into())
    }
}

/// Metadata for a compiled or pending-compilation trace.
#[derive(Clone, Debug)]
pub struct StubEntry {
    /// Unique identifier for this trace.
    pub trace_id: TraceId,
    /// Opcodes in this trace.
    pub opcodes: Vec<OpCode>,
    /// LLVM IR text (generated by ir.rs).
    pub ir_text: Option<String>,
    /// Number of times this trace has been executed.
    pub exec_count: u64,
    /// Whether this trace is marked as "hot" for compilation.
    pub is_hot: bool,
    /// Native function pointer (set after compilation; None if not yet compiled).
    /// In a real JIT, this would be: `Option<extern "C" fn() -> i64>`
    /// For now, we store it as a placeholder.
    pub native_fn: Option<usize>,
}

impl StubEntry {
    /// Create a new stub entry for a trace.
    pub fn new(trace_id: TraceId, opcodes: Vec<OpCode>) -> Self {
        StubEntry {
            trace_id,
            opcodes,
            ir_text: None,
            exec_count: 0,
            is_hot: false,
            native_fn: None,
        }
    }

    /// Increment execution counter and check if trace became hot.
    pub fn record_execution(&mut self) -> bool {
        self.exec_count += 1;
        if !self.is_hot && self.exec_count >= HOT_THRESHOLD {
            self.is_hot = true;
            true  // Became hot just now
        } else {
            false
        }
    }

    /// Mark this trace as requiring IR emission and attempt native compilation.
    pub fn generate_ir(&mut self) {
        use crate::ir::emit_ir;
        let ir = emit_ir(&self.trace_id.0, &self.opcodes);
        self.ir_text = Some(ir.clone());

        // Attempt native compilation via llc/opt pipeline
        if let Some(fn_ptr) = crate::compile::try_compile_trace(&self.trace_id.0, &ir) {
            self.native_fn = Some(fn_ptr);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// JIT Engine
// ─────────────────────────────────────────────────────────────────────────────

/// The JIT stub layer. Manages traces and marks hot paths for compilation.
pub struct JitEngine {
    /// Map from trace ID to stub entry.
    stubs: HashMap<TraceId, StubEntry>,
    /// Hot traces awaiting compilation (IR text available).
    pub hot_traces: Vec<(TraceId, String)>,
    /// Statistics
    pub stats: JitStats,
}

/// JIT execution statistics.
#[derive(Clone, Debug, Default)]
pub struct JitStats {
    /// Total traces tracked.
    pub total_traces: usize,
    /// Traces marked as hot.
    pub hot_traces_count: usize,
    /// Traces with compiled native code.
    pub compiled_traces: usize,
    /// Total executions across all traces.
    pub total_executions: u64,
}

impl JitEngine {
    /// Create a new JIT engine.
    pub fn new() -> Self {
        JitEngine {
            stubs: HashMap::new(),
            hot_traces: Vec::new(),
            stats: JitStats::default(),
        }
    }

    /// Register a new trace for JIT tracking.
    pub fn register_trace(&mut self, trace_id: TraceId, opcodes: Vec<OpCode>) {
        if self.stubs.len() < MAX_STUBS {
            self.stubs.insert(trace_id.clone(), StubEntry::new(trace_id, opcodes));
            self.stats.total_traces += 1;
        }
    }

    /// Record execution of a trace. Returns true if trace became hot.
    pub fn record_trace_execution(&mut self, trace_id: &TraceId) -> bool {
        if let Some(stub) = self.stubs.get_mut(trace_id) {
            let became_hot = stub.record_execution();
            self.stats.total_executions += 1;

            if became_hot {
                stub.generate_ir();
                self.stats.hot_traces_count += 1;
                // Add to hot traces queue for external compilation
                if let Some(ir_text) = stub.ir_text.clone() {
                    self.hot_traces.push((trace_id.clone(), ir_text));
                }
            }
            became_hot
        } else {
            false
        }
    }

    /// Get a stub entry (read-only).
    pub fn get_stub(&self, trace_id: &TraceId) -> Option<&StubEntry> {
        self.stubs.get(trace_id)
    }

    /// Set native function pointer for a compiled trace.
    pub fn set_native_fn(&mut self, trace_id: &TraceId, fn_ptr: usize) {
        if let Some(stub) = self.stubs.get_mut(trace_id) {
            stub.native_fn = Some(fn_ptr);
            self.stats.compiled_traces += 1;
        }
    }

    /// Collect all hot traces as (trace_id, IR text) pairs.
    pub fn collect_hot_traces(&self) -> Vec<(String, String)> {
        self.stubs
            .values()
            .filter(|stub| stub.is_hot && stub.ir_text.is_some())
            .map(|stub| (stub.trace_id.0.clone(), stub.ir_text.clone().unwrap()))
            .collect()
    }

    /// Dump JIT stats as a formatted string.
    pub fn stats_string(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(
            s,
            "JIT Stats:\n  Total traces: {}\n  Hot traces: {}\n  Compiled: {}\n  Total executions: {}",
            self.stats.total_traces,
            self.stats.hot_traces_count,
            self.stats.compiled_traces,
            self.stats.total_executions
        );
        s
    }
}

impl Default for JitEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trace_id_creation() {
        let tid = TraceId::from_index(42);
        assert_eq!(tid.0, "trace_42");

        let tid2 = TraceId::from_name("my_loop");
        assert_eq!(tid2.0, "my_loop");
    }

    #[test]
    fn stub_entry_creation() {
        let opcodes = vec![OpCode::Push(1), OpCode::Push(2), OpCode::Add];
        let stub = StubEntry::new(TraceId::from_index(0), opcodes.clone());
        assert_eq!(stub.exec_count, 0);
        assert!(!stub.is_hot);
        assert_eq!(stub.opcodes.len(), 3);
    }

    #[test]
    fn record_execution_counts_correctly() {
        let opcodes = vec![OpCode::Push(1)];
        let mut stub = StubEntry::new(TraceId::from_index(0), opcodes);

        // Record executions up to HOT_THRESHOLD
        for i in 0..HOT_THRESHOLD {
            let became_hot = stub.record_execution();
            if i + 1 < HOT_THRESHOLD {
                assert!(!became_hot);
            } else {
                assert!(became_hot);
            }
        }
        assert!(stub.is_hot);
    }

    #[test]
    fn jit_engine_register_trace() {
        let mut jit = JitEngine::new();
        let trace_id = TraceId::from_index(0);
        let opcodes = vec![OpCode::Push(42), OpCode::Halt];

        jit.register_trace(trace_id.clone(), opcodes);
        assert_eq!(jit.stats.total_traces, 1);
        assert!(jit.get_stub(&trace_id).is_some());
    }

    #[test]
    fn jit_engine_record_execution() {
        let mut jit = JitEngine::new();
        let trace_id = TraceId::from_index(0);
        let opcodes = vec![OpCode::Push(1)];

        jit.register_trace(trace_id.clone(), opcodes);

        // Record executions until hot
        for i in 0..HOT_THRESHOLD {
            let became_hot = jit.record_trace_execution(&trace_id);
            if i + 1 == HOT_THRESHOLD {
                assert!(became_hot);
                assert_eq!(jit.stats.hot_traces_count, 1);
            }
        }
    }

    #[test]
    fn jit_engine_ir_generation_on_hot() {
        let mut jit = JitEngine::new();
        let trace_id = TraceId::from_index(0);
        let opcodes = vec![OpCode::Push(10), OpCode::Halt];

        jit.register_trace(trace_id.clone(), opcodes);

        // Execute until hot
        for _ in 0..HOT_THRESHOLD {
            jit.record_trace_execution(&trace_id);
        }

        let stub = jit.get_stub(&trace_id).unwrap();
        assert!(stub.is_hot);
        assert!(stub.ir_text.is_some());
        let ir = stub.ir_text.as_ref().unwrap();
        assert!(ir.contains("define i64 @trace_0()"));
    }

    #[test]
    fn jit_engine_max_stubs_limit() {
        let mut jit = JitEngine::new();

        // Try to register more than MAX_STUBS
        for i in 0..MAX_STUBS + 50 {
            let trace_id = TraceId::from_index(i);
            let opcodes = vec![OpCode::Push(i as i32)];
            jit.register_trace(trace_id, opcodes);
        }

        assert_eq!(jit.stats.total_traces, MAX_STUBS);
    }

    #[test]
    fn jit_engine_collect_hot_traces() {
        let mut jit = JitEngine::new();

        // Register and heat up three traces
        for i in 0..3 {
            let trace_id = TraceId::from_index(i);
            let opcodes = vec![OpCode::Push(i as i32)];
            jit.register_trace(trace_id.clone(), opcodes);

            for _ in 0..HOT_THRESHOLD {
                jit.record_trace_execution(&trace_id);
            }
        }

        let hot = jit.collect_hot_traces();
        assert_eq!(hot.len(), 3);
        for (tid, ir) in &hot {
            assert!(tid.starts_with("trace_"));
            assert!(ir.contains("define i64 @"));
        }
    }

    #[test]
    fn jit_engine_set_native_fn() {
        let mut jit = JitEngine::new();
        let trace_id = TraceId::from_index(0);
        let opcodes = vec![OpCode::Push(1)];

        jit.register_trace(trace_id.clone(), opcodes);
        jit.set_native_fn(&trace_id, 0xDEADBEEF);

        let stub = jit.get_stub(&trace_id).unwrap();
        assert_eq!(stub.native_fn, Some(0xDEADBEEF));
        assert_eq!(jit.stats.compiled_traces, 1);
    }

    #[test]
    fn jit_engine_stats_string() {
        let mut jit = JitEngine::new();
        let trace_id = TraceId::from_index(0);
        let opcodes = vec![OpCode::Push(1)];

        jit.register_trace(trace_id, opcodes);

        let stats = jit.stats_string();
        assert!(stats.contains("JIT Stats"));
        assert!(stats.contains("Total traces: 1"));
    }

    #[test]
    fn jit_engine_multiple_traces_different_hot_times() {
        let mut jit = JitEngine::new();

        // Register trace 0
        let tid0 = TraceId::from_index(0);
        jit.register_trace(tid0.clone(), vec![OpCode::Push(0)]);

        // Register trace 1
        let tid1 = TraceId::from_index(1);
        jit.register_trace(tid1.clone(), vec![OpCode::Push(1)]);

        // Heat up trace 0
        for _ in 0..HOT_THRESHOLD {
            jit.record_trace_execution(&tid0);
        }

        // Verify only trace 0 is hot
        assert!(jit.get_stub(&tid0).unwrap().is_hot);
        assert!(!jit.get_stub(&tid1).unwrap().is_hot);
        assert_eq!(jit.stats.hot_traces_count, 1);

        // Heat up trace 1
        for _ in 0..HOT_THRESHOLD {
            jit.record_trace_execution(&tid1);
        }

        // Now both are hot
        assert!(jit.get_stub(&tid0).unwrap().is_hot);
        assert!(jit.get_stub(&tid1).unwrap().is_hot);
        assert_eq!(jit.stats.hot_traces_count, 2);
    }

    #[test]
    fn jit_engine_no_panic_on_unknown_trace() {
        let mut jit = JitEngine::new();
        let unknown_id = TraceId::from_name("unknown");

        let became_hot = jit.record_trace_execution(&unknown_id);
        assert!(!became_hot);
        assert!(jit.get_stub(&unknown_id).is_none());
    }
}
